---
kind: pipeline
name: ruby2.5

steps:
  - name: RSpec
    image: ruby:2.5
    commands:
      - rm -rf Gemfile.lock | true
      - bundle install
      - bundle exec rspec
...
---
kind: pipeline
name: ruby2.7

steps:
  - name: rspec
    image: ruby:2.7
    commands:
      - rm -rf Gemfile.lock | true
      - bundle install
      - bundle exec rspec
