---
kind: pipeline
name: 'Ruby 2.4.x'
trigger:
  event:
    - push

steps:
  - name: RSpec
    image: ruby:2.4
    commands:
      - rm -rf Gemfile.lock | true
      - bundle install
      - bundle exec rspec

---
kind: pipeline
name: 'Ruby 2.5.x'
trigger:
  event:
    - push

steps:
  - name: RSpec
    image: ruby:2.5
    commands:
      - rm -rf Gemfile.lock | true
      - bundle install
      - bundle exec rspec
...
